### PR TITLE
Fix: charset index numbers being treated as roman numerals

### PR DESCRIPTION
**Pull request by petermbenjamin**
In markdown, decimals get treated as roman numerals.
Therefore, `1.` gets displayed as `i`, `2.` as `ii`, and so on.

I tried to improve the README to make it more readable by replaced the unordered list (e.g. bullet point list) with a 2-column table.

### CODE REVIEW

**Comment by briandowns** [comment]
Thanks for this PR. Looks good. Would you mind including the char sets up to index 43 while you have this open?

**Comment by petermbenjamin** [comment]
@briandowns , sure. Do you have the charset symbols you'd like me to add as well? or just the indexes for now?

**Comment by briandowns** [comment]
Adding these should due.  https://github.com/briandowns/spinner/blob/master/character_sets.go#L47-L51 

Thanks!

**Comment by petermbenjamin** [comment]
Done.

**Comment by briandowns** [comment]
LGTM pending Travis.

**Comment by briandowns** [comment]
Thanks again for this nice addition.

**Pull request merged**
