### PR TITLE
Ignore ANSI sequences when measuring string width

### PR DESCRIPTION
**Pull request by e-zim**
### Summary

Hello! This PR updates the `computeNumberOfLinesNeededToPrintStringInternal` function to ignore ANSI sequences from the string width measurement since these are not visibly printed to the terminal.

Currently, ANSI sequences are included in this measurement which can cause the computed number of lines to be greater than the actual number of lines needed to print a string. When this happens, previous lines are unexpectedly erased from the screen.

#### Before changes

https://user-images.githubusercontent.com/18134219/215296896-480c8231-90ff-4a0f-ba7d-8fd009cd4d79.mov

#### After changes

https://user-images.githubusercontent.com/18134219/215296872-285cd1b8-e74c-4e85-ae7f-b05c37b46822.mov

### Reviewers

The following snippet can be used to demonstrate the erasure behavior on a terminal of width 80: 

```golang
package main

import (
	"time"

	"github.com/briandowns/spinner"
)

func main() {
	s := spinner.New(spinner.CharSets[9], 100*time.Millisecond)
	s.Suffix = " \x1b[36mHere we are.\x1b[0m Waiting ever so \x1b[1;33mpatiently\x1b[0m as we watch the spinner spin."

	s.Start()
	time.Sleep(2 * time.Second)
	s.Stop()
}
```

To test these changes, checkout this branch and update your `go.mod` to include:

```golang
replace github.com/briandowns/spinner v1.20.0 => ../path-to-branch/spinner
```

### Notes

- The `computeNumberOfLinesNeededToPrintStringInternal` function was updated to measure the line count in an iterative manner.
- Tests for the `computeNumberOfLinesNeededToPrintStringInternal` function were updated to use a table-driven testing approach. New tests were also added for checking expected behavior of strings containing ANSI sequences.

### CODE REVIEW

**Comment by briandowns** [comment]
Thank you for this!

**Comment by shinji62** [comment]
@briandowns Can we get a new release ? I am impacted by this issues as well.

**Comment by briandowns** [comment]
All set @shinji62 ! https://github.com/briandowns/spinner/releases/tag/v1.21.0

**Comment by shinji62** [comment]
Wow that's was fast !

**Comment by mwbrooks** [comment]
Fantastic, thank you for the release @briandowns! 🙇🏻 🚀

**Comment by briandowns** [comment]
No prob. :D

**Pull request merged**
